
stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
    outs:
      - data/processed/
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/
    outs:
      - model.pkl
